### ISSUE TITLE
file not recognized: File format not recognized

### ISSUE THREAD

**Issue by HomoRiron** [bwmarrin/dgvoice#14]
# command-line-arguments
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\Users\username\AppData\Local\Temp\go-link-619833591\go.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status

**Comment by bwmarrin** [comment]
Got me.  Can you maybe add a detailed description of what you were doing?  Maybe show the command you entered to come about this error?   Without some context there's no way I can help here :(
