### ISSUE TITLE
Questions about managing audio playback

### ISSUE THREAD

**Issue by importnil** [bwmarrin/dgvoice#2]
Hello,

Can you please propose on solutions for the following tasks (using this library):
1) Pausing the audio.
2) Finding out whether the audio ended playing/was paused/resumed.
3) How do you play the audio that's being downloaded? Currently I'm downloading youtube videos with github.com/otium/ytdl lib, but can't play them until the files are not fully downloaded.

Thank you.

**Comment by bwmarrin** [comment]
Okay, none of this works out of the box with dgvoice but it's all possible.  It's actually all being done with the bruxism musicplugin but, I'll warn you now that code isn't the cleanest.

https://github.com/iopred/bruxism/tree/master/musicplugin

I'll try to spend some time on dgvoice though and add some examples of the above here. Meanwhile, read  though the musicplugin code and see if that helps get you going.  Hit me up on Discord if you run into any questions.
